
trigger:
	- main

- name: "Set flag for APP VERSION"
  env:
    APP_Ver: ${{ contains(github.event.pull_request.body, '[APP Ver]') }}
  run: |
  echo "flag=${APP_Ver}" >> $GITHUB_ENV
  echo "set flag to ${APP_Ver}"